package com.bitpunchlab.android.pawsgo


enum class AppState {
    NORMAL,
    LOGGED_IN,
    LOGGED_OUT,
    INCORRECT_CREDENTIALS,

    EMAIL_ALREADY_EXISTS,
    EMAIL_SERVER_ERROR,

    READY_CREATE_USER_AUTH,
    ERROR_CREATE_USER_AUTH,
    READY_CREATE_USER_FIREBASE,
    SUCCESS_CREATED_USER_ACCOUNT,
    ERROR_CREATE_USER_ACCOUNT,

    LOST_DOG_REPORT_SENT_SUCCESS,
    LOST_DOG_REPORT_SENT_ERROR,

    MESSAGE_SENT_SUCCESS,
    MESSAGE_SENT_ERROR,

    CHANGE_PASSWORD_SUCCESS,
    CHANGE_PASSWORD_INCORRECT,
    CHANGE_PASSWORD_ERROR,

    RESET_EMAIL_SENT,
    EMAIL_INVALID,
    RESET_EMAIL_ERROR,

    CONFIRM_DELETE_REPORT,

    DELETE_REPORT_SUCCESS,
    DELETE_REPORT_ERROR,

    RESET
}

enum class TypeOfPet {
    Dog,
    Cat,
    Bird,
    Other,
    All
}

